#!/bin/sh
# check if the directory exists
if [ -d ~/cy/ ]; then
  # move into the directory
  cd ~/cy/
  # pull the repository
  git pull
else
  # create the directory
  mkdir ~/cy/
  git clone https://github.com/cyber-prophet/cy ~/cy/
fi

nu ~/cy/kickstart/setup-cy.nu

# output a message to the user
echo "Cy is installed. Type nu in your terminal, and it will start with cy."
